version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - simnet
  redis:
    image: redis:7.4-alpine
    container_name: redis
    restart: always
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - redis_data:/data
    networks:
      - simnet
  client-gateway:
    container_name: client-gateway
    build: ./apps/client-gateway
    ports:
      - ${CLIENT_GATEWAY_PORT}:3001
    volumes:
      - ./apps/client-gateway/src:/usr/src/app/src
    command: npm run start:dev
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_GATEWAY_QUEUE=${RABBITMQ_GATEWAY_QUEUE}
      - RABBITMQ_SERVICE=${RABBITMQ_SERVICE}
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - GATEWAY_PORT=${CLIENT_GATEWAY_PORT}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_CLIENT=${REDIS_CLIENT}
      - REDIS_SIMULATION_CHANNEL=${REDIS_SIMULATION_CHANNEL}
      - REDIS_SIMULATION_NAMESPACE=${REDIS_SIMULATION_NAMESPACE}
      - REDIS_SIMULATION_EVENT=${REDIS_SIMULATION_EVENT}
    networks:
      - simnet
  lab-backend:
    container_name: nest-backend-lab
    build: ./apps/aquaculture-lab-backend
    ports:
      - ${BACKEND_PORT}:3001
    volumes:
      - ./apps/aquaculture-lab-backend/src:/usr/src/app/src
    command: npm run start:dev
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_GATEWAY_QUEUE=${RABBITMQ_GATEWAY_QUEUE}
      - RABBITMQ_SIMULATIONS_QUEUE=${RABBITMQ_SIMULATIONS_QUEUE}
      - RABBITMQ_SERVICE=${RABBITMQ_SERVICE}
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - BACKEND_PORT=${BACKEND_PORT}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_CLIENT=${REDIS_CLIENT}
    networks:
      - simnet
  lab-frontend:
    container_name: angular-frontend-lab
    build: ./apps/aquaculture-lab-frontend
    ports:
      - "4200:4200"
    volumes:
      - ./apps/aquaculture-lab-frontend:/app
      - /app/node_modules
    environment:
      - REDIS_SIMULATION_CHANNEL=${REDIS_SIMULATION_CHANNEL}
      - REDIS_SIMULATION_NAMESPACE=${REDIS_SIMULATION_NAMESPACE}
      - REDIS_SIMULATION_EVENT=${REDIS_SIMULATION_EVENT}
      - GATEWAY_URL=${GATEWAY_URL}
    command: npm run start
    depends_on:
      - client-gateway
    networks:
      - simnet
  python-worker:
    build: ./apps/worker
    container_name: python-worker
    volumes:
      - ./apps/worker:/app
    environment:
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_SIMULATIONS_QUEUE=${RABBITMQ_SIMULATIONS_QUEUE}
      - RABBITMQ_SERVICE=${RABBITMQ_SERVICE}
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_SIMULATION_CHANNEL=${REDIS_SIMULATION_CHANNEL}
      - REDIS_SIMULATION_NAMESPACE=${REDIS_SIMULATION_NAMESPACE}
      - REDIS_SIMULATION_EVENT=${REDIS_SIMULATION_EVENT}
    depends_on:
      - rabbitmq
    networks:
      - simnet

networks:
  simnet:
    driver: bridge

volumes:
  redis_data: