version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - simnet
  client-gateway:
    container_name: client-gateway
    build: ./client-gateway
    ports:
      - ${CLIENT_GATEWAY_PORT}:3001
    volumes:
      - ./client-gateway/src:/usr/src/app/src
    command: npm run start:dev
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_SIMULATIONS_QUEUE=${RABBITMQ_SIMULATIONS_QUEUE}
      - RABBITMQ_SERVICE=${RABBITMQ_SERVICE}
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - NESTJS_PORT=${CLIENT_GATEWAY_PORT}
    networks:
      - simnet
  lab-backend:
    container_name: nest-backend-lab
    build: ./aquaculture-lab-backend
    ports:
      - "3000:3000"
    volumes:
      - ./aquaculture-lab-backend/src:/usr/src/app/src
    command: npm run start:dev
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
    networks:
      - simnet
  python-worker:
    build: ./worker
    container_name: python-worker
    volumes:
      - ./worker:/app
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
    depends_on:
      - rabbitmq
    networks:
      - simnet

networks:
  simnet:
    driver: bridge